############################################################
############################################################
####################### TEMPLATES ##########################
############################################################
############################################################
app_index:
    path: /
    controller: App\Controller\DefaultController::index
    
app_maintenance:
    path: /telemaintenance
    controller: App\Controller\DefaultController::maintenance

app_downloads:
    path: /telechargements
    controller: App\Controller\DefaultController::downloads
    
app_whoarewe:
    path: /qui_sommes_nous
    controller: App\Controller\DefaultController::whoarewe
    
app_chart:
    path: /qui_sommes_nous/charte
    controller: App\Controller\DefaultController::charte
    
app_knowhow:
    path: /savoir_faire
    controller: App\Controller\DefaultController::knowhow
    
app_services:
    path: /services
    controller: App\Controller\DefaultController::services
    
app_reference:
    path : /references
    controller: App\Controller\DefaultController::reference
    
############################################################
############################################################
######################## TICKETTING ########################
############################################################
############################################################
app_maintenance_index_ticket:
    path : /ticket_de_maintenance
    controller: App\Controller\TickettingController::index

app_maintenance_new_ticket:
    path : /ticket_de_maintenance/new
    controller: App\Controller\TickettingController::new
    
app_maintenance_edit_ticket:
    path : /ticket_de_maintenance/edit
    controller: App\Controller\TickettingController::edit
    
app_maintenance_delete_ticket:
    path : /ticket_de_maintenance/delete
    controller: App\Controller\TickettingController::delete
    
############################################################
############################################################
######################## TICKETTING ########################
############################################################
############################################################